# docker-compose file setting up local testing environment for AWS services alongside serverless plugins
# Feel free to comment out unnused services

version: '3.8'
services:
    
    serverless-container:                                               # Setting up Serverless development environment        
        image: esteveslima/slvmm-image:latest           
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/slvmm                                                 # Using the entire project folder as volume for development
            - ./resources/config/aws/.aws:/home/node/.aws               # Setting up AWS credentials inside the container(~/.aws)
        working_dir: /slvmm     
        environment:
            - NODE_TLS_REJECT_UNAUTHORIZED=0                            # Fixing SSL/TLS errors in local development environment(only to enable sls offline https endpoints)
        restart: "no"
        depends_on:            
            - dynamodb-container            
        expose:
            - "4000-4010"
        ports:
            - "9229:9229"                                               # VSCode debugger port
            - "4000:4000"                                               # SLS offline debugger            

    dynamodb-container:                                                 # Setting up DynamoDB local testing environment with dynamoDB local
        image: amazon/dynamodb-local
        restart: always        
        command: "-jar DynamoDBLocal.jar -port 8000 -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
        working_dir: /home/dynamodblocal
        user: root
        volumes:
            - "./.volumes/.dynamodb-storage:/home/dynamodblocal/data"
        expose:
            - '8000'
        ports:
            - '8000:8000'                                                # shell available at http://localhost:8000/shell/