#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Runs on post-commit hook(after commit)

# TODO: fix script to offer the option to create lerna versions on every commit(???)
exit 0; # DISABLED

# use lerna to prompt an option for updating modified packages versions(with changelogs and new commit)
# exec < /dev/tty     # assigns stdin to keyboard 
# npx lerna version --conventional-commits --no-push --no-commit-hooks --ignore-scripts  # lerna command is freezing terminal, requiring to exit with ctrl+c
# exec <&-            # restore stdin

## another possible option...(propted a weird heap error)
# npx lerna changed -l
# exec < /dev/tty     # assigns stdin to keyboard 
# while true; do
#     read -p "Update versions with lerna? (y/n) " yn
#     case $yn in
#         [Yy]* ) npx lerna version --conventional-commits --no-push --yes & (sleep 5 && exit 0); break;;
#         [Nn]* ) break;;
#         * ) ;;
#     esac
# done