#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

printf "\n\n\n";
exec < /dev/tty
while true; do
    read -p "Commit with commitzen? (Y/n) " yn
    case $yn in
        [Yy]* ) npx git-cz --hook || true; break;;
        [Nn]* ) break;;
        * ) npx git-cz --hook || true; break;;
    esac
done